### ISSUE TITLE
argument

### ISSUE THREAD

**Issue by Li-An** [asamuzaK/withExEditorHost#21]
Hello, I try to make your plugin work on CentBrowser (Chrome) - Windows 10 64 bits - but did not know what to put for cmdArgs - I use a Markdown editor, MarkdownEdit.

I’ve got 
*Host Connection Disconnected
Host Version Incompatible*
message

**Comment by asamuzaK** [comment]
When launching MarkdownEdit, are you putting arguments to the startup path?
If you do not have it, I think that it is not necessary to input anything when setting withExEditorHost.

However, I do not know about MarkdownEdit so it may be wrong.
Please read the explanation about the command line option in the official document of MarkdownEdit.

> Host Version Incompatible

Make sure you got Node.js 8.9.0 or higher installed.

Thanks.

**Comment by asamuzaK** [comment]
By the way,

> CentBrowser

It is not listed as supported browsers.
Do you know if CentBrowser share registries with chrome?

**Comment by Li-An** [comment]
Thanks for your quick answer. I downloaded today Node.js so I suppose it’s the last version.
No argument needed for MarkdownEdit I think (but how to indicate this when running the installation of your script?).
I will ask for the registries.

**Comment by asamuzaK** [comment]
> but how to indicate this when running the installation of your script?

It's on README

> I will ask for the registries.

I installed CentBrowser and tested myself.
Yes, it did share registries with Chrome.
I'll add CentBrowser config later.

**Comment by asamuzaK** [comment]
> I'll add CentBrowser config later.

Done.

**Comment by asamuzaK** [comment]
You can use MarkdownEdit now?

**Comment by Li-An** [comment]
OK, when I right click in a field, the menu is showing now "edit text with withExEditor" but nothing is launching and I suppose I have to modify my config file.
Content in editorconfig.json
```
{
  "editorPath": "C:\\Program Files (x86)\\MarkdownEdit\\bin\\mde.exe",
  "cmdArgs": [
 ],
  "fileAfterCmdArgs": true
}
```

**Comment by asamuzaK** [comment]
Open browser console (Ctrl + Shift + J)
Do you see any error related to the host?

**Comment by Li-An** [comment]
See the capture 
![2017-11-27_10h39_41](https://user-images.githubusercontent.com/689870/33260365-e48d5bd4-d35f-11e7-9ac8-b73ce4302d87.png)

I did not notice but I still have the warnings **Disconnected** and **Incompatible**.

**Comment by asamuzaK** [comment]
That's web console.
Log of browser console please.
There should be something like:
```
withexeditorhost: ...
```

**Comment by Li-An** [comment]
Sorry to be so noobish but when I type  (Ctrl + Shift + J) I have this console. I searched for Browser Console but did not find anything else.

**Comment by asamuzaK** [comment]
Oh, sorry.
I forgot you are using Blink based browser.

**Comment by asamuzaK** [comment]
I'll test locally.
Is this the one you are using?
[Markdown Edit | Mike-Ward.Net](http://mike-ward.net/markdownedit/ "Markdown Edit | Mike-Ward.Net")

**Comment by asamuzaK** [comment]
Installed Markdown Edit and ran host setup.js.
It worked fine...
Tested on Firefox and Chrome Canary.

**Comment by Li-An** [comment]
OK, I tried it with Firefox 57 and it works. In C:\Users\profile\AppData\Roaming\withexeditorhost\config I have only a Firefox directory. Should I have a one relative to CentBrowser?

**Comment by Li-An** [comment]
Works in Waterfox. Same problem in Vivaldi (disconnected, incompatible).

**Comment by asamuzaK** [comment]
For CentBrowser, you should create host for Chrome, not Firefox.
Choose `chrome` when you run setup.js

Or, the latest host v2.1.3 has CentBrowser support.
[Releases · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/releases "Releases · asamuzaK/withExEditorHost")
Download latest host, complete install, and then run setup.js again.
```
> npm install
> node setup.js
```

**Comment by Li-An** [comment]
It’s OK now! You are a chief. Don’t know why/how i created a **firefox** folder (default one?) but it works with **chrome**. 
Thanks a lot for your time and your work. This kind of extension is very important for me as I write a lot of posts in WordPress in Markdown language and it’s much more convenient in an external application.
Thanks again.
